# Generated by Django 5.0.4 on 2024-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Nama', models.CharField(max_length=30)),
                ('Employment_Status', models.CharField(max_length=10)),
                ('Monthly_Performance', models.DecimalField(decimal_places=2, max_digits=10))
            ],
        ),
    ]
