# Generated by Django 5.0.4 on 2024-04-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeePerformance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Target',
        ),
    ]
