# Generated by Django 5.0.4 on 2024-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePerformance', '0002_employee_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='foto',
            field=models.ImageField(default='blank profile pic.png', upload_to='images/'),
        ),
    ]
